### ISSUE TITLE
`make instalcheck` doesn't work due to python spookiness

### ISSUE THREAD

**Issue by d** [d/bug-free-fortnight#4]
<details>
  <summary>

click to expand error message</summary>

```
env PGOPTIONS='-c optimizer=on' make installcheck-good
make -C src/test installcheck-good
make[1]: Entering directory `/build/gpdb/src/test'
make -C regress installcheck-good
make[2]: Entering directory `/build/gpdb/src/test/regress'
make -C ../../../src/port all
make[3]: Entering directory `/build/gpdb/src/port'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/build/gpdb/src/port'
make -C ../../../contrib/spi refint.so autoinc.so
make[3]: Entering directory `/build/gpdb/contrib/spi'
make[3]: `refint.so' is up to date.
make[3]: `autoinc.so' is up to date.
make[3]: Leaving directory `/build/gpdb/contrib/spi'
rm -rf ./testtablespace
mkdir ./testtablespace
./checkinc.py
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "./checkinc.py", line 3, in <module>
    import sys, os, re, subprocess
ImportError: No module named os
make[2]: *** [includecheck] Error 1
make[2]: Leaving directory `/build/gpdb/src/test/regress'
make[1]: *** [installcheck-good] Error 2
make[1]: Leaving directory `/build/gpdb/src/test'
make: *** [installcheck-good] Error 2
```

</details>
@oarap and @hsyuan found this out

**Comment by oarap** [comment]
```
env PGOPTIONS='-c optimizer=on' make installcheck-good
make -C src/test installcheck-good
make[1]: Entering directory `/build/gpdb/src/test'
make -C regress installcheck-good
make[2]: Entering directory `/build/gpdb/src/test/regress'
make -C ../../../src/port all
make[3]: Entering directory `/build/gpdb/src/port'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/build/gpdb/src/port'
make -C ../../../contrib/spi refint.so autoinc.so
make[3]: Entering directory `/build/gpdb/contrib/spi'
make[3]: `refint.so' is up to date.
make[3]: `autoinc.so' is up to date.
make[3]: Leaving directory `/build/gpdb/contrib/spi'
rm -rf ./testtablespace
mkdir ./testtablespace
./checkinc.py
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "./checkinc.py", line 3, in <module>
    import sys, os, re, subprocess
ImportError: No module named os
make[2]: *** [includecheck] Error 1
make[2]: Leaving directory `/build/gpdb/src/test/regress'
make[1]: *** [installcheck-good] Error 2
make[1]: Leaving directory `/build/gpdb/src/test'
make: *** [installcheck-good] Error 2
```
